#!/bin/dash


#If any additional arguments are given
if [ "$#" -ne 0 ]; then 
    echo "usage: tigger-log"
    exit 1
fi

#If tigger repository is not found 
if ! [ -d .tigger ]; then
    echo "tigger-log: error: tigger repository directory .tigger not found"
    exit 1
fi

tac .tigger/log.txt