#!/bin/dash

# If more arguments are given after command
if [ "$#" -gt 0 ]; then
    echo "usage: tigger-init"
    exit 1
fi

# If .tigger directory already exists
if [ -d .tigger ]; then
    echo "tigger-init: error: .tigger already exists"
    exit 1
fi

# Create .tigger directory
mkdir .tigger
mkdir .tigger/index
mkdir .tigger/commits
touch .tigger/log.txt
echo "Initialized empty tigger repository in .tigger"